name: CI CD

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

env:
  DOTNET_VERSION: 5.0.300
  CONFIGURATION: Release

jobs:
  build-test:    
    runs-on: ubuntu-latest   
    name: Build and test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}     
    - name: Build
      run: dotnet build ArnabDeveloper.HttpHealthCheck/ArnabDeveloper.HttpHealthCheck.csproj --configuration ${{ env.CONFIGURATION }}
    - name: Test
      run: dotnet test ArnabDeveloper.HttpHealthCheck.Test/ArnabDeveloper.HttpHealthCheck.Test.csproj --configuration ${{ env.CONFIGURATION }}

  github-nuget-push:
    if: ${{ github.event_name == 'push' || github.event_name == 'release' }}
    runs-on: ubuntu-latest
    needs: build-test
    name: GitHub nuget push
    steps:
    - name: Checkout code
      uses: actions/checkout@v2      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}        
    - name: Build
      run: dotnet build ArnabDeveloper.HttpHealthCheck/ArnabDeveloper.HttpHealthCheck.csproj --configuration ${{ env.CONFIGURATION }}
    - name: Create nuget package
      run: dotnet pack ArnabDeveloper.HttpHealthCheck/ArnabDeveloper.HttpHealthCheck.csproj --configuration ${{ env.CONFIGURATION }}
    - name: Push nuget package
      run: dotnet nuget push "ArnabDeveloper.HttpHealthCheck/bin/Release/ArnabDeveloper.HttpHealthCheck.1.0.4.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/Arnab-Developer/index.json" --skip-duplicate

  nuget-org-push:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    needs: build-test
    name: nuget org push
    environment:
      name: "nuget"
      url: "https://www.nuget.org/packages/ArnabDeveloper.HttpHealthCheck"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}        
    - name: Build
      run: dotnet build ArnabDeveloper.HttpHealthCheck/ArnabDeveloper.HttpHealthCheck.csproj --configuration ${{ env.CONFIGURATION }}
    - name: Create nuget package
      run: dotnet pack ArnabDeveloper.HttpHealthCheck/ArnabDeveloper.HttpHealthCheck.csproj --configuration ${{ env.CONFIGURATION }}
    - name: Push nuget package
      run: dotnet nuget push "ArnabDeveloper.HttpHealthCheck/bin/Release/ArnabDeveloper.HttpHealthCheck.1.0.4.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate